repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - name: Check semantic commit message
        id: conventional-pre-commit
        stages: [commit-msg]
