name: 'Test private repo'

on:
  pull_request:
    branches: [ main ]


permissions:
  packages: write


jobs:
  build-base-docker:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      dockerfile: .base.docker
      registry: ghcr.io
      tags: ghcr.io/${{ github.repository }}/base:${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.sha }}
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  check-repo:
    needs: [build-base-docker]
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/${{ github.repository }}/base:${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.sha }}
        credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check private repo
        run: python -m checker --help

