name: 'Test private repo'

on:
  pull_request:
    branches: [ main ]


env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ github.repository }}/base
  IMAGE_TAG: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.sha }}


jobs:
  build-base-docker:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      dockerfile: .base.docker
      registry: ${{ env.REGISTRY }}
      tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }}
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  check:
    needs: [build-base-docker]
    runs-on: ubuntu-latest
    container:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }}
        credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check private repo
        run: python -m checker --help

