name: 'Test private repo'

on:
  pull_request:
    branches: [ main ]


jobs:
  build-base-docker:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      dockerfile: .docker
      target: testenv
      tags: testenv:${{ github.sha }}
      artifact: true
      artifact_name: testenv.tar
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  check-repo:
    needs: [build-base-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: testenv.tar
          path: .

      - name: Load Docker Image
        run: |
          docker load -i testenv.tar

      - name: Check private repo
        run:
          # RUN: python -m /opt/checker check -- CODE_DIR"
          docker run \
            --rm \
            -v ${{ github.workspace }}:/workspace \
            testenv:${{ github.sha }} \
            "python -m /opt/checker check -- /workspace"
